config/routes.rb
ReneescobarNet::Application.routes.draw do
  
devise_for :users, path: "", path_names: { sign_in: 'login', 
                                               sign_out: 'logout', 
                                               password: 'secret', 
                                               confirmation: 'verification',  
                                               registration: 'register', 
                                               sign_up: 'join' }

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/'
    resources :pages 
    resources :users
  end

  root "pages#home_page"

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
	has_ancestry
	
	PAGE_TYPE = %w(Home News Video Contact About Portfolio Blog)

	validates_presence_of :title, :body
	validates_uniqueness_of :title
	# validates :page_type, inclusion: PAGE_TYPE

	# Callbacks - be sure they don't interact with other models
	# Scopes 
	scope :home, -> { where(page_type: 'Home', is_published: 1).limit(1) }


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
  	before_action :authenticate_admin


  	protected 

  	def admin_user?
  		user_signed_in? && current_user.admin?
  	end

  	def authenticate_admin
  		unless admin_user?
  		  redirect_to new_user_session_path, alert: "Only Administrators Allowed" 
  		end
  	end
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
	class DashboardController < BaseController
	  def index
	  end
	end
end

app/controllers/admin/pages_controller.rb
module Admin
	class PagesController < BaseController
	  before_action :load_page, only: [:edit, :show, :update, :destroy]

	  def index
	  	@pages = Page.all
	  end

	  def new 
	  	@page = Page.new
	  end

	  def show 
	  end

	  def create
	  	@page = Page.new(page_params)
	  	if @page.save
	  		flash[:notice] = 'Page has successfully been saved'
	  		redirect_to action: :show, id: @page
	  	else
	  		render action: :new
	  	end
	  end
	  
	  def edit 

	  end 

	  def update
	  	if @page.update(page_params)
	  		flash[:notice] = 'Page has successfully been saved'
	  		redirect_to action: :show, id: @page
	  	else
	  		render action: :edit
	  	end
	  end

	  def destroy
	  end

	  private 

	  def load_page
	  	@page = Page.find(params[:id])
	  end

	  def page_params
	  	params.require(:page).permit(:parent_id, :body, :title, :description, :keywords, :is_published, :slug, :ancestry)
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	

	def home_page
		@page = Page.home.first
		if @page.present?
			render :show, :object => @page
		else
			render :instructions
		end
	end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
  
  def admin_form_for(object, options={}, &proc)
    options = options.dup
    options[:builder] ||= AdminFormBuilder
    options[:html] ||= {}
    options[:html][:class] ||= 'horizontal-form'

    form_for(object, options, &proc)
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/base/_flash_messages.html.erb
<% flash.each do |type, message| %>
	<div class="alert <%= bootstrap_class_for(type) %> fade in">
		<button class="close" data-dismiss='alert'>x</button>
		<%= message %>
	</div>
<% end %>

app/views/admin/base/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
		
  </div> <!-- container-->
</div>

app/views/admin/base/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rene Escobar || Web Developer</title>
  <%= stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

app/views/admin/base/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		  <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to '<span class="glyphicon glyphicon-home"></span> Admin Home'.html_safe, admin_path %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-bookmark"></span> Pages'.html_safe, admin_pages_path %></li>
			</ul>
		</div>
	</div>
</nav>
	

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/admin/pages/_form.html.erb
<div class="well bs-component">
<%= admin_form_for [:admin, @page], :html => {:multipart => true}  do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :title, label: 'Page Title' %>
  <%= f.text_field :keywords %>
  <%= f.text_field :description %>
  <%= f.check_box :is_published, label: 'Published' %>
   <%= f.collection_select :parent_id, Page.order(:title), :id, :title, include_blank: true %>
  <%= f.cktext_area :body, rows: 30, ckeditor: { :uiColor => '#303030', :toolbar => 'mini'}  %>
  <%= f.submit %>
<% end %>	
</div>

app/views/admin/pages/edit.html.erb
<h4>Edit Page</h4>

<%= render 'form' %>

app/views/admin/pages/index.html.erb
<h3>Pages</h3>
<!-- page_type, title, body, is_published -->
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Title</th>
			<th>Page Type</th>
			<th>Body</th>
			<th>Published?</th>
			<th></th>
		</tr>
	</thead>
	<% @pages.each do |p| %>
	<tbody>
		<tr>
			<td><%= p.title %></td>
			<td><%= p.page_type %></td>
			<td><%= p.body.html_safe %></td>
			<td><%= p.is_published %></td>
			<td>
				<%= link_to 'Show', admin_page_path(p) %>
				<%= link_to 'Edit', edit_admin_page_path(p) %>
				<%= link_to 'Destroy'  %>
			</td>		
		</tr>
	</tbody>
	<% end %>
</table>
<%= link_to 'Add Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h4>New Page</h4>
<%= render 'form' %>

app/views/admin/pages/old_form.html.erb
<form class="form-horizontal">
  <fieldset>
    <legend>New Page</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
      <div class="col-lg-10">
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
        <div class="checkbox">
          <label>
            <input type="checkbox"> Checkbox
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Textarea</label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" id="code" name="code"></textarea>
        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-2 control-label">Radios</label>
      <div class="col-lg-10">
        <div class="radio">
          <label>
            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
            Option one is this
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
            Option two can be something else
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="select" class="col-lg-2 control-label">Selects</label>
      <div class="col-lg-10">
        <select class="form-control" id="select">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
        <br>
        <select multiple="" class="form-control">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>

app/views/application/_footer.html.erb
<div class="container">

</div>

<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
</body>
</html>

app/views/application/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rene Escobar || Web Developer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<header class="masthead">
		<h3 class='masthead-title'>@webdevescobar</h3>
	</header>
	

app/views/application/_navigation.html.erb
<ul class="nav">
	<li><%= link_to 'Home', root_path %></li>
</ul>

app/views/layouts/application.html.erb
<%= render 'header' %>
<%= render 'navigation' %>
<div class="container">
<%= render partial: "flash_messages", flash: flash %> 
	<%= yield %>
</div> <!-- end container -->
<%= render 'footer' %>

app/views/pages/instructions.html.erb
<h2>Getting Started</h2>

<p>In order to get the Home page up and running you must first publish the page</p>

<p>To execute run <code>rake db:seed</code></p>

<p>This will create an example page and a User Account with admin privileges</p>

app/views/pages/show.html.erb
<%= raw @page.body %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>